import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]


[env]
term = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = 'JetBrainsMono Nerd Font'

[window]
dimensions = { columns = 170, lines = 40 }
startup_mode = "Windowed"
decorations = 'buttonless'
dynamic_padding = true
opacity = 0.75
blur = true
